### ISSUE TITLE
Include HDF5 support in PyPI packages

### ISSUE THREAD

**Issue by speth** [Cantera/pypi-packages#3]
Cantera 3.0 adds "native" support for working with HDF5 files using libhdf5. I believe supporting this feature with the PyPI packages will require compiling libhdf5 as part of the build process and embedding it in the wheels. Perhaps we can borrow from what `h5py` does on this front?

This is a parallel to Cantera/conda-recipes#43, but all of the implementation challenges are distinct for PyPI packages.

**Comment by bryanwweber** [comment]
Thanks for asking this question @speth. In principle, we don't actually have to compile libhdf5 if we can make it available on the build machine somehow; in practice, this will probably mean compiling on at least Windows. The recommended practice for wheels is to copy the related libraries into the wheel and munge the naming to avoid conflicts if libraries load the same thing. This is done semi-automatically at the end of the `cibuildwheel` process by a couple of packages depending on the OS. I think the one for Linux is called `auditwheel`. So assuming that the fixer package can correctly read the dependencies out of the linked Cantera library, this should be able to be handled.

The h5py wheel building config is here: https://github.com/h5py/h5py/blob/master/ci/azure-pipelines-wheels.yml It seems like they install libhdf5 on the builder machines with a specific version: https://github.com/h5py/h5py/blob/49d7b8cde724a69a50d6cd4b218df7a6ba141633/ci/azure-pipelines-wheels.yml#L9-L12 The HDF5 version configuration appears to be here: https://github.com/h5py/h5py/blob/master/azure-pipelines.yml#L57 and it's apparently built-in to their linux image for building Linux wheels.

So it appears at least h5py only builds for 1 version of HDF5, although they test against several. This is probably fine for wheels, because they bring the whole world of dependencies with them, so we shouldn't need to worry about different wheels' dependencies stomping on each other.

Another big question is what to do about the sdist, which is currently also used to build the wheels. The `setup.py` script is already approaching the complexity where I want to introduce an external build system. So far, we've been including all the dependencies in the sdist and compiling them into libcantera, aside from Boost which must be provided by the user. Since libhdf5 will be the first binary dependency where we don't include the source code, I wonder what will be the best way to support this.

The last time I fixed the wheels earlier this year, I looked at using [enscons](https://github.com/dholth/enscons) as the build backend so that we could leverage SCons at build time to resolve system dependencies and such. I was scared off by the fact that there hasn't been a release in almost 2 years and the project seems basically inactive. I'm not sure if that means its stable or what, but I wasn't confident enough to rely on it.

If we keep building the sdist the way we do right now, including all the relevant Cantera C/C++ sources in the tarball, we may want to look at something like [mesonbuild](https://mesonbuild.com/) or [scikit-build-core](https://scikit-build-core.readthedocs.io/en/latest/) as the build backend. Those two packages are widely used (SciPy and NumPy for Meson, scikit-build for a number of ML related projects). They should both allow users to configure search paths at build time to be able to find system dependencies.

Alternatively, we could stop distributing the sdist and just build the wheels using SCons. I'm less confident in this approach being able to maintain ABI compatibility with Python standards, especially on Linux and I'd prefer to defer to a specific purpose built build runner for this (cibuildwheel is the standard).

**Comment by speth** [comment]
Thanks for the notes on this, @bryanwweber. While I think this is a problem worth solving eventually, it's probably too much of a lift for the Cantera 3.0 release.

**Comment by bryanwweber** [comment]
Very helpfully, h5py has an open (as of today) PR to move their builds to GHA. Planning to copy a lot of that for at least hdf5 support :smile: https://github.com/h5py/h5py/pull/2444
